<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="style.css" />
        <meta charset="utf-8" />
        <title>MP</title>
    </head>
    <body>
     <h1>Elektronické přihlašování do seminářů</h1>
     <table>
  <tr>
    <th><br></th>
    <th>Blok1</th>
    <th>Blok2</th>
    <th>Blok3</th>
    <th>Blok4</th>
  </tr>
  <tr>
    <td>Student1</td>
    <td><form action="" method="post"><input type="submit" name="Blok1" value="Blok1"></form></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student2</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student3</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student4</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student5</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student6</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student7</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student8</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student9</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Student10</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>
    </body>
</html>
